[package]
name = "cool_easy_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.56"
quote = "1.0.26"
syn = "1.0.102"
syn-rsx = "0.9.0"
markdown = "0.3"